### ISSUE TITLE
RAL support broken with security.serializer=json config

### ISSUE THREAD

**Issue by rjd1** [choria-plugins/puppet-agent#32]
With mcollective_choria::config security.serializer set to json the functionality of mco puppet resource no longer works. This happens with both the new choria-server and old mcollective daemons. 

Example and log output:

```
[user@puppet ~]$ mco puppet resource service ntpd ensure=running

 * [ ============================================================> ] 2 / 2


puppet.example.com          Unknown Request Status
   undefined method `downcase' for nil:NilClass

node.example.com Unknown Request Status
   undefined method `downcase' for nil:NilClass


Summary of Changed:

     No aggregate summary could be computed


Finished processing 2 / 2 hosts in 10.13 ms

[user@puppet ~]$

E, [2018-11-02T12:26:53.445585+00:00 #11444] ERROR -- : agent.rb:108:in `rescue in handlemsg' puppet#resource failed: NoMethodError: undefined method `downcase' for nil:NilClass
E, [2018-11-02T12:26:53.445661+00:00 #11444] ERROR -- : agent.rb:109:in `rescue in handlemsg' /opt/puppetlabs/mcollective/plugins/mcollective/agent/puppet.rb:142:in `block in <class:Puppet>'
    /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/rpc/agent.rb:86:in `handlemsg'
    /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/agents.rb:126:in `block (2 levels) in dispatch'
    /opt/puppetlabs/puppet/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
    /opt/puppetlabs/puppet/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
    /opt/puppetlabs/puppet/lib/ruby/2.4.0/timeout.rb:33:in `catch'
    /opt/puppetlabs/puppet/lib/ruby/2.4.0/timeout.rb:33:in `catch'
    /opt/puppetlabs/puppet/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
    /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/mcollective/agents.rb:125:in `block in dispatch'
```

**Comment by ripienaar** [comment]
Thanks @rjd1, if you're able to test this fix in the PR on your side that'd be great, for me this seems to solve it.

Before:

```
% mco puppet resource service ntpd ensure=running -I dev1
....
dev1                           Unknown Request Status
   undefined method `downcase' for nil:NilClass
```

after

```
dev1
   Changed: true
    Result: ensure changed 'stopped' to 'running'


Summary of Changed:

   Changed = 1
```
```

**Comment by rjd1** [comment]
Yeah, the fix looks good in my testing. That was fast, thanks!

**Comment by ripienaar** [comment]
Thanks @rjd1 I will make a official release soon
